package backend.enums;


public enum EPermission {
    ADMIN_CREATE,
    ADMIN_READ,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    ADMIN_REVOKED,
    ADMIN_BAN,
    MANAGER_CREATE,
    MANAGER_READ,
    MANAGER_UPDATE,
    MANAGER_DELETE,
    MANAGER_REVOKED,
    MANAGER_BAN,
    CUSTOMER_READ,
    CUSTOMER_UPDATE,
}
